path:
  pdf_path: "C:/Users/Administrator/Desktop/11111212312.pdf"
  word_file_path: "C:/Users/Administrator/Desktop/test/"

#parameter:
#  pool_size: 5
#  charset: "utf-8"
#name:
#  book: 朝花夕拾
#  books: 三体
